### ISSUE TITLE
drf_yasg errors when you attempt to start label_studio for all versions> 1.4.1 and  < 1.6.0

### ISSUE THREAD

**Issue by Blowoffvalve** [mhw32/data-centric-deep-learning#7]
Attempting to run label-studio with the version information available in the dockerfile and requirements.txt causes the error below
`=> Database and media directory: /home/gitpod/.local/share/label-studio
=> Static URL is set to: /static/
Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.8.16/bin/label-studio", line 8, in <module>
    sys.exit(main())
  File "/home/gitpod/.pyenv/versions/3.8.16/lib/python3.8/site-packages/label_studio/server.py", line 282, in main
    _setup_env()
  File "/home/gitpod/.pyenv/versions/3.8.16/lib/python3.8/site-packages/label_studio/server.py", line 40, in _setup_env
    application = get_wsgi_application()
  File "/home/gitpod/.pyenv/versions/3.8.16/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/gitpod/.pyenv/versions/3.8.16/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/gitpod/.pyenv/versions/3.8.16/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/gitpod/.pyenv/versions/3.8.16/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/gitpod/.pyenv/versions/3.8.16/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/gitpod/.pyenv/versions/3.8.16/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gitpod/.pyenv/versions/3.8.16/lib/python3.8/site-packages/label_studio/core/settings/label_studio.py", line 43, in <module>
    from label_studio.core.utils.common import collect_versions
  File "/home/gitpod/.pyenv/versions/3.8.16/lib/python3.8/site-packages/label_studio/core/utils/common.py", line 36, in <module>
Starting new HTTPS connection (1): o227124.ingest.sentry.io:443
    from drf_yasg.inspectors import CoreAPICompatInspector, NotHandled
  File "/home/gitpod/.pyenv/versions/3.8.16/lib/python3.8/site-packages/drf_yasg/inspectors/__init__.py", line 5, in <module>
    from .field import (
  File "/home/gitpod/.pyenv/versions/3.8.16/lib/python3.8/site-packages/drf_yasg/inspectors/field.py", line 406, in <module>
    (serializers.NullBooleanField, (openapi.TYPE_BOOLEAN, None)),
AttributeError: module 'rest_framework.serializers' has no attribute 'NullBooleanField'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
[https://o227124.ingest.sentry.io:443](https://o227124.ingest.sentry.io/) "POST /api/5820521/store/ HTTP/1.1" 200 41`

**Comment by mhw32** [comment]
See fix here: https://github.com/mhw32/data-centric-deep-learning/pull/8
